export const FETCH_ALL_POSTS_SUCCESS = "FETCH_ALL_POSTS_SUCCESS"
export const FETCH_ALL_POSTS_FAIL = "FETCH_ALL_POSTS_FAIL"

export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_POST_FAIL = "CREATE_POST_FAIL";

export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";
export const DELETE_POST_FAIL = "DELETE_POST_FAIL";

export const UPDATE_POST_SUCCESS = "UPDATE_POST_SUCCESS";
export const UPDATE_POST_FAIL = "UPDATE_POST_FAIL";